/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SearchEngine = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const AIAssistantActivity = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'task' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const AIAssistantMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SecurityLevel = IDL.Variant({
  'safest' : IDL.Null,
  'safer' : IDL.Null,
  'standard' : IDL.Null,
});
export const CRMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'parentId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCRMessage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addSearchEngine' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssistantActivity' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createAssistantMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createThread' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllAuditItems' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getAllIdentityItems' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getAllSearchEngines' : IDL.Func([], [IDL.Vec(SearchEngine)], ['query']),
  'getAssistantActivities' : IDL.Func(
      [],
      [IDL.Vec(AIAssistantActivity)],
      ['query'],
    ),
  'getAssistantMessages' : IDL.Func(
      [],
      [IDL.Vec(AIAssistantMessage)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSecurityLevel' : IDL.Func([], [SecurityLevel], ['query']),
  'getThreadMessages' : IDL.Func([IDL.Nat], [IDL.Vec(CRMessage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeSearchEngine' : IDL.Func([IDL.Nat], [], []),
  'resetAuditChecklist' : IDL.Func([], [], []),
  'resetIdentityChecklist' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAuditItem' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setIdentityItem' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setSecurityLevel' : IDL.Func([IDL.Text], [], []),
  'toggleAuditItem' : IDL.Func([IDL.Text], [], []),
  'toggleIdentityItem' : IDL.Func([IDL.Text], [], []),
  'updateAssistantActivityStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SearchEngine = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const AIAssistantActivity = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'task' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const AIAssistantMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SecurityLevel = IDL.Variant({
    'safest' : IDL.Null,
    'safer' : IDL.Null,
    'standard' : IDL.Null,
  });
  const CRMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'parentId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCRMessage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addSearchEngine' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssistantActivity' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createAssistantMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createThread' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllAuditItems' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getAllIdentityItems' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getAllSearchEngines' : IDL.Func([], [IDL.Vec(SearchEngine)], ['query']),
    'getAssistantActivities' : IDL.Func(
        [],
        [IDL.Vec(AIAssistantActivity)],
        ['query'],
      ),
    'getAssistantMessages' : IDL.Func(
        [],
        [IDL.Vec(AIAssistantMessage)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSecurityLevel' : IDL.Func([], [SecurityLevel], ['query']),
    'getThreadMessages' : IDL.Func([IDL.Nat], [IDL.Vec(CRMessage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeSearchEngine' : IDL.Func([IDL.Nat], [], []),
    'resetAuditChecklist' : IDL.Func([], [], []),
    'resetIdentityChecklist' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAuditItem' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setIdentityItem' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setSecurityLevel' : IDL.Func([IDL.Text], [], []),
    'toggleAuditItem' : IDL.Func([IDL.Text], [], []),
    'toggleIdentityItem' : IDL.Func([IDL.Text], [], []),
    'updateAssistantActivityStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };