/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIAssistantActivity {
  'id' : bigint,
  'status' : string,
  'task' : string,
  'timestamp' : bigint,
}
export interface AIAssistantMessage {
  'id' : bigint,
  'content' : string,
  'timestamp' : bigint,
}
export interface CRMessage {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'parentId' : bigint,
}
export interface SearchEngine {
  'id' : bigint,
  'url' : string,
  'name' : string,
  'description' : string,
}
export type SecurityLevel = { 'safest' : null } |
  { 'safer' : null } |
  { 'standard' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCRMessage' : ActorMethod<[bigint, bigint, string], bigint>,
  'addSearchEngine' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssistantActivity' : ActorMethod<[string], bigint>,
  'createAssistantMessage' : ActorMethod<[string], bigint>,
  'createThread' : ActorMethod<[string, string], bigint>,
  'getAllAuditItems' : ActorMethod<[], Array<[string, boolean]>>,
  'getAllIdentityItems' : ActorMethod<[], Array<[string, boolean]>>,
  'getAllSearchEngines' : ActorMethod<[], Array<SearchEngine>>,
  'getAssistantActivities' : ActorMethod<[], Array<AIAssistantActivity>>,
  'getAssistantMessages' : ActorMethod<[], Array<AIAssistantMessage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSecurityLevel' : ActorMethod<[], SecurityLevel>,
  'getThreadMessages' : ActorMethod<[bigint], Array<CRMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeSearchEngine' : ActorMethod<[bigint], undefined>,
  'resetAuditChecklist' : ActorMethod<[], undefined>,
  'resetIdentityChecklist' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAuditItem' : ActorMethod<[string, boolean], undefined>,
  'setIdentityItem' : ActorMethod<[string, boolean], undefined>,
  'setSecurityLevel' : ActorMethod<[string], undefined>,
  'toggleAuditItem' : ActorMethod<[string], undefined>,
  'toggleIdentityItem' : ActorMethod<[string], undefined>,
  'updateAssistantActivityStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];